language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
before_install:
  - cd $TRAVIS_BUILD_DIR
install:
  - pip install -r requirements.txt
  - pip install pytest-cov coveralls requests-mock pytest-mock
script:
  - flask test --coverage
after_success:
  - coveralls
env:
  - FLASK_APP=app/app.py