language: python
python:
  - "3.5"
  - "3.6"
before_install:
  - cd $TRAVIS_BUILD_DIR
install:
  - pip install -r requirements.txt
script:
  - ls -lah
  - flask
  - flask test
env:
  - FLASK_APP=app/app.py